version: "3.9"
services:
  api:
    container_name: server_rupay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    image: api_image:latest
    pull_policy: build
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_rupay
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./app.env

volumes:
  db:
