version: "3.9"
services:
  api:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_rupay
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./app.env

volumes:
  db:
