version: "3.9"
services:
  api:
    container_name: rupay-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    image: api_image:latest
    pull_policy: build
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: rupay-postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./app.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d rupay"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    pull_policy: build
    container_name: rupay-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migration/:/migration
    command:
      [
        "-path",
        "/migration",
        "-database",
        "postgresql://root:secret@postgres:5432/rupay?sslmode=disable",
        "up",
      ]

volumes:
  db:
