version: "3.9"
services:
  api:
    container_name: rupay-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    image: api_image:latest
    pull_policy: build
    depends_on:
      - postgres
    networks:
      - rupay

  postgres:
    image: postgres:latest
    container_name: rupay-postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d rupay"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rupay

volumes:
  db:

networks:
  rupay:
    external: true
